### ISSUE TITLE
Failing on more complex scenarios

### ISSUE THREAD

**Issue by sinkingsugar** [rokups/nim-coro#1]
Great library! looks way more neat then the standard `coro.nim`
However on windows at least more complex scenarios seems to crash.
e.g.:
```nim
when isMainModule:
    var ctx, ctx2: ptr Coroutine

    proc doo() =
        echo "DOO"
        discard ctx.switch()
        echo "DOO 2"
    
    proc foo() =
        echo "FOO"
        discard ctx2.switch()
        echo "FOO 2"
        discard ctx2.switch()

    threadToCoroutine()
    ctx = Coroutine.new(foo)
    ctx2 = Coroutine.new(doo)
    
    discard ctx.switch()

    ctx.delete()
    ctx2.delete()

    echo "END"
```

**Comment by rokups** [comment]
Yes i am aware. Unfortunately at the time i have no need of this functionality so i can not dedicate any time. Some serious rework is needed i believe.

**Comment by sinkingsugar** [comment]
Sounds good! I guessed you were busy elsewhere :)
I'll close this for now, maybe one day I will have a look at it!
